services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
    container_name: postgres-demo
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-social_network-docker-postgres
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/social_network
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
